[palettes.akari]
background = '#1C1A17'
foreground = '#E6DED3'
current_line = '#3A3530'
primary = '#1C1A17'
box = '#3A3530'
blue = '#5A6F82'
cyan = '#6F8F8A'
green = '#7FAF6A'
orange = '#F08A5D'
pink = '#9A8FB3'
purple = '#7C6A8A'
red = '#C84C32'
yellow = '#E26A3B'
lantern = '#E26A3B'
comment = '#7A7A75'
